services:
  - type: web
    name: atlan-customer-support-copilot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python ingest.py && streamlit run app.py --server.port $PORT
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false